# `numpy
- one of the core packages for numerical computing in Python
- many packages are built on top of numpy
- 'numpy' has been optimized for processing: faster due to memory access

In [ ]:
#import Numpy with standard abbreviation
import numpy as np 

# Variables
We can think about variables as a name we assign to a particular object in Python. For example:

In [2]:
# assign a small array to a vraible a 
#np.array- making an array , list of a list. first row is 1,1,2
a = np.array([ [1,1,2], [3,5,8] ])

WHen we run the cell, we store the variable and its value. We can see the variable's value in two ways:

In [3]:
a
#two rows three columns

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## naming variables
In the class, we are going to use 'snake_case' for naming variables. 

# Variables and objects
**object**: often encountered in Python documentation and tutorials.
- a bundle of properties and actions about something specific
ex) 
- object: data frame
- properties: number of rows, names of columns, data made
- actions: selecting a row, adding a column 

A variable is a name we give a specific object, and the same object can be referenced by different variables. 

ex)
- The Sun = object
- sol = spanish word for sun = variable 
- soleil = French word for sun = another variable 

In practice, we will use object and variable interchangeably. 

# Types

Each object in Python has a type. 

type = what kind of object it is. 

We can also call the type of the object, the **class** of the object. 
We can see the type/class of an object by using the `type` function:

In [5]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing:

In [6]:
print(a[0,0])
#accessing the first row and the first column
type(a[0,0])

1


numpy.int64

In [7]:
#how would you access the value 5 in the array a 
print(a[1,1])

5


# Functions
`print` was our exxample of a Python function!
A function:
- take in a set of **arguments**, separated by commas, and
- use those arguments to produce some **output**

argument = parameter: you might see argument more often in the documentation 
We can ask information about a function by executing `?` followed by the following function name:

In [8]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in paranthesis
- then a short description of what the function does 
- finally, a list of the arguments and a brief explanation of each of them.

Different types of arguments inside the paranthesis. Roughly speaking, there are two types of arguments:
- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional argments**: arguments that are pre-filled with a default value by the function, but we can override them. Optional arguments appear inside the paranthesis () in the form 

`optional argument = default_value`

In [9]:
print('changing the dedault end argument of the print function' , end = ':)')

changing the dedault end argument of the print function:)